version: '3.4'

services:
  flasknote:
    image: flasknote
    expose:
      - "5000"
    ports:
      - "5000:5000"
  
  flasknote:
    image: noteweb
    expose:
      - "3000"
    ports:
      - "3000:3000"
